name: mercure-monaisegment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - libpng
  - libjpeg-turbo
  - jupyterlab
  - cudatoolkit=11.1
  - matplotlib
  - pip
  - pip :
    - numpy>=1.21
    - highdicom==0.21.1
    - typeguard==2.12.1
    - monai==1.1.0
    - monai-deploy-app-sdk==0.5.0
    - nibabel==4.0.2
    - pydicom==2.3.1
    - scikit-learn==1.0.2
    - simpleitk==2.2.1
    - torch==1.11.0
    - torchvision==0.12.0
    