name: mercure-monaisegment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - libpng
  - libjpeg-turbo
  - pytorch
  - torchvision
  - jupyterlab
  - cudatoolkit=11.1
  - matplotlib
  - pip
  - pip :
    - monai
    - torch>=1.10.2
    - numpy>=1.21
    - nibabel>=3.2.1
    - pydicom>=1.4.2
    - highdicom>=0.18.2
    - SimpleITK>=2.0.0
    - typeguard~=2.12.1 # Work around MONAI requirements.txt bug that picks up the wrong typeguard version
    - scikit-learn 
    - monai-deploy-app-sdk
